"""Stage 3 — Interview LLM logic.

The hiring manager (an AI character generated by ensayo for each company)
conducts a guided interview with the student. Phases are steered by the
system prompt — introduction, motivation, role-specific, behavioural,
candidate questions, close — over a soft target of 10 turns.

After the interview ends, a separate scoring call produces structured
feedback used to advance the application or reject it.
"""

from __future__ import annotations

import json
import os
from typing import Any

import httpx

from workready_api.models import AssessmentResult, FeedbackDetail


# Soft target for total student-manager exchanges. The manager is told to
# wrap up naturally when approaching this. Either side can end early.
TARGET_TURNS = 10
WRAP_UP_AFTER = 8  # turn after which the manager is steered toward closing


# --- System prompt builder ---


def build_interview_system_prompt(
    manager_persona: str,
    job_title: str,
    company_name: str,
    job_description: str,
    resume_score: int | None = None,
    resume_strengths: list[str] | None = None,
    resume_gaps: list[str] | None = None,
    cover_letter: str | None = None,
) -> str:
    """Build the system prompt for the interview LLM session.

    Wraps the manager's existing chatbot persona with interview-specific
    guidance: phases to cover, turn awareness, when to wrap up, how to
    adapt to the resume's strength.
    """
    score_context = ""
    if resume_score is not None:
        if resume_score >= 75:
            tone = (
                "The candidate's resume was strong (scored {0}/100). You can "
                "be confident in your questions and explore depth on their "
                "claimed experience."
            ).format(resume_score)
        elif resume_score >= 50:
            tone = (
                "The candidate's resume was decent (scored {0}/100). Probe "
                "for examples and detail to verify their suitability."
            ).format(resume_score)
        else:
            tone = (
                "The candidate's resume was weak (scored {0}/100) but they "
                "made it to interview. Give them a fair chance — ask gentle "
                "but searching questions to see if they have hidden potential."
            ).format(resume_score)
        score_context = f"\n\nRESUME CONTEXT:\n{tone}"

    if resume_strengths:
        score_context += "\n\nThe assessor flagged these strengths:\n"
        for s in resume_strengths[:3]:
            score_context += f"  - {s}\n"

    if resume_gaps:
        score_context += "\nThe assessor flagged these gaps to probe:\n"
        for g in resume_gaps[:3]:
            score_context += f"  - {g}\n"

    cover_context = ""
    if cover_letter and len(cover_letter) > 50:
        cover_context = (
            f"\n\nCOVER LETTER (the candidate wrote this):\n"
            f"\"\"\"\n{cover_letter[:1500]}\n\"\"\""
        )

    return f"""{manager_persona}

═══════════════════════════════════════════════════════════
You are conducting a job interview for the role of {job_title} at {company_name}.

This is a real conversation with a student in an educational simulation.
Stay in character as the hiring manager throughout. Speak as you would
to a real candidate — warm but professional, curious, evaluating.

JOB DESCRIPTION (this is the role you're hiring for):
\"\"\"
{job_description[:2500]}
\"\"\"
{score_context}{cover_context}

INTERVIEW STRUCTURE
You have approximately {TARGET_TURNS} exchanges to cover these phases naturally:

  1. WELCOME & ICEBREAKER
     "Hi, thanks for coming in. Tell me a bit about yourself."

  2. MOTIVATION & RESEARCH
     "What drew you to {company_name} specifically? / What do you know
     about us?"

  3. ROLE-SPECIFIC QUESTIONS
     Ask about how they'd approach the actual responsibilities of this
     role. Reference the job description.

  4. BEHAVIOURAL QUESTIONS
     "Tell me about a time when..." / "How did you handle...?"

  5. CANDIDATE QUESTIONS
     "Do you have any questions for me about the role or the team?"

  6. CLOSE
     "Thanks, that's everything from me. We'll be in touch."

GUIDELINES:
- Speak conversationally, in first person, as the manager character
- Ask ONE question at a time and wait for the answer
- Adapt to what the candidate says — follow up on interesting points
- Be warm but don't fawn. Be honest but not harsh.
- After turn {WRAP_UP_AFTER}, start steering toward the close
- When you're ready to end, finish with a clear closing statement
- DO NOT mention scores, the simulation, or that you're an AI
- DO NOT break character

Begin with your opening message."""


# --- LLM client (uses the same provider config as the resume assessor) ---


async def chat_completion(
    system_prompt: str,
    messages: list[dict],
) -> str:
    """Send a chat-style request to the configured LLM provider.

    messages is a list of {"role": "user"|"assistant", "content": str}
    representing the conversation so far. Returns the assistant's reply text.

    Uses the same env var setup as the resume assessor:
    - LLM_PROVIDER: stub | ollama | anthropic | openrouter
    - LLM_MODEL: model name
    - provider-specific keys
    """
    provider = os.environ.get("LLM_PROVIDER", "stub").lower()

    if provider == "stub":
        return _stub_reply(messages)

    if provider == "anthropic":
        return await _anthropic_chat(system_prompt, messages)

    if provider == "openrouter":
        return await _openrouter_chat(system_prompt, messages)

    if provider == "ollama":
        return await _ollama_chat(system_prompt, messages)

    return _stub_reply(messages)


def _stub_reply(messages: list[dict]) -> str:
    """Deterministic stub for development without an LLM."""
    turn = sum(1 for m in messages if m["role"] == "assistant")
    if turn == 0:
        return (
            "Hi, thanks for coming in today. Before we get started, "
            "tell me a bit about yourself and what brought you to apply for this role."
        )
    if turn < WRAP_UP_AFTER:
        prompts = [
            "Interesting. Can you give me a specific example of when you've done that?",
            "What would you say is your biggest strength for this role?",
            "Tell me about a challenge you've overcome recently.",
            "How do you approach learning something new?",
            "What do you know about our company and what we do?",
            "Where do you see yourself in two years?",
        ]
        return prompts[turn % len(prompts)]
    if turn == WRAP_UP_AFTER:
        return "Thanks for those answers. Do you have any questions for me about the role or the team?"
    return "Great, thanks for your time today. We'll be in touch within a few days. Take care."


async def _anthropic_chat(system_prompt: str, messages: list[dict]) -> str:
    api_key = os.environ.get("ANTHROPIC_API_KEY", "")
    model = os.environ.get("LLM_MODEL", "claude-sonnet-4-20250514")
    async with httpx.AsyncClient(timeout=60.0) as client:
        resp = await client.post(
            "https://api.anthropic.com/v1/messages",
            json={
                "model": model,
                "max_tokens": 800,
                "system": system_prompt,
                "messages": messages,
            },
            headers={
                "x-api-key": api_key,
                "anthropic-version": "2023-06-01",
                "content-type": "application/json",
            },
        )
        resp.raise_for_status()
    return resp.json()["content"][0]["text"].strip()


async def _openrouter_chat(system_prompt: str, messages: list[dict]) -> str:
    api_key = os.environ.get("OPENROUTER_API_KEY", "")
    model = os.environ.get("LLM_MODEL", "anthropic/claude-sonnet-4")
    full_messages = [{"role": "system", "content": system_prompt}] + messages
    async with httpx.AsyncClient(timeout=60.0) as client:
        resp = await client.post(
            "https://openrouter.ai/api/v1/chat/completions",
            json={
                "model": model,
                "messages": full_messages,
                "max_tokens": 800,
            },
            headers={
                "Authorization": f"Bearer {api_key}",
                "content-type": "application/json",
            },
        )
        resp.raise_for_status()
    return resp.json()["choices"][0]["message"]["content"].strip()


async def _ollama_chat(system_prompt: str, messages: list[dict]) -> str:
    base_url = os.environ.get("OLLAMA_BASE_URL", "http://localhost:11434")
    model = os.environ.get("LLM_MODEL", "llama3.2")
    api_key = os.environ.get("OLLAMA_API_KEY", "")
    full_messages = [{"role": "system", "content": system_prompt}] + messages
    headers = {}
    if api_key:
        headers["Authorization"] = f"Bearer {api_key}"
    async with httpx.AsyncClient(timeout=120.0) as client:
        resp = await client.post(
            f"{base_url}/api/chat",
            json={"model": model, "messages": full_messages, "stream": False},
            headers=headers,
        )
        resp.raise_for_status()
    return resp.json()["message"]["content"].strip()


# --- Final assessment ---


ASSESSMENT_SYSTEM_PROMPT = """You are an HR assessor reviewing an interview
transcript for an educational simulation. The interview was conducted by a
hiring manager character with a real student.

Provide a structured assessment in JSON format with these exact fields:

{
  "fit_score": <0-100>,
  "communication": <0-100>,
  "preparation": <0-100>,
  "cultural_fit": <0-100>,
  "role_awareness": <0-100>,
  "asked_good_questions": true/false,
  "strengths": ["...", "..."],
  "gaps": ["...", "..."],
  "suggestions": ["...", "..."],
  "tailoring": "One sentence on how well they targeted this specific role",
  "proceed_to_role": true/false,
  "summary": "2-3 sentence summary of the interview"
}

Be realistic but encouraging. This is for an educational simulation where
students are learning to interview. Focus on actionable feedback they can
use to improve."""


def build_assessment_user_prompt(
    job_title: str,
    company_name: str,
    transcript: list[dict],
) -> str:
    transcript_text = "\n\n".join(
        f"{'MANAGER' if m['role'] == 'assistant' else 'CANDIDATE'}: {m['content']}"
        for m in transcript
    )
    return f"""Assess this interview for the {job_title} role at {company_name}.

INTERVIEW TRANSCRIPT:
{transcript_text}

Return ONLY valid JSON matching the schema above."""


async def assess_interview(
    job_title: str,
    company_name: str,
    transcript: list[dict],
) -> AssessmentResult:
    """Run the final assessment LLM call. Returns AssessmentResult."""
    provider = os.environ.get("LLM_PROVIDER", "stub").lower()

    if provider == "stub" or not transcript:
        return _stub_assessment(transcript)

    user_prompt = build_assessment_user_prompt(job_title, company_name, transcript)
    raw = await chat_completion(
        ASSESSMENT_SYSTEM_PROMPT,
        [{"role": "user", "content": user_prompt}],
    )
    return _parse_assessment(raw)


def _stub_assessment(transcript: list[dict]) -> AssessmentResult:
    """Rule-based assessment stub for development."""
    student_turns = [m for m in transcript if m["role"] == "user"]
    total_words = sum(len(m["content"].split()) for m in student_turns)
    avg_words = total_words / max(len(student_turns), 1)

    score = min(int(avg_words * 1.5 + len(student_turns) * 5), 100)
    proceed = score >= 50

    return AssessmentResult(
        fit_score=score,
        feedback=FeedbackDetail(
            strengths=(
                ["Engaged throughout the conversation"] if len(student_turns) >= 5 else []
            ),
            gaps=(
                ["Answers were quite brief — develop with examples"]
                if avg_words < 20
                else []
            ),
            suggestions=[
                "Use the STAR method (Situation, Task, Action, Result) for behavioural questions",
                "Prepare 2-3 thoughtful questions about the role and company",
            ],
            tailoring=(
                "The candidate engaged with the role but could have referenced "
                "the company more specifically."
            ),
        ),
        proceed_to_interview=proceed,  # field name is reused for "proceed to next stage"
        message=(
            "You came across well. We'd like to invite you to the next stage."
            if proceed
            else "Thank you for the conversation. Unfortunately we won't be progressing."
        ),
    )


def _parse_assessment(raw: str) -> AssessmentResult:
    """Parse JSON assessment response from the LLM."""
    cleaned = raw.strip()
    if cleaned.startswith("```"):
        first_nl = cleaned.find("\n")
        if first_nl != -1:
            cleaned = cleaned[first_nl + 1:]
        if cleaned.endswith("```"):
            cleaned = cleaned[:-3]
        cleaned = cleaned.strip()

    data: dict[str, Any] = json.loads(cleaned)

    return AssessmentResult(
        fit_score=int(data.get("fit_score", 50)),
        feedback=FeedbackDetail(
            strengths=data.get("strengths", []),
            gaps=data.get("gaps", []),
            suggestions=data.get("suggestions", []),
            tailoring=data.get("tailoring", ""),
        ),
        proceed_to_interview=bool(data.get("proceed_to_role", False)),
        message=data.get("summary", ""),
    )
